[platformio]
src_dir     = task4/submission
include_dir = task4/submission

[env:vsdsquadron_mini]
platform = ch32v
board = vsdsquadronMini
framework = noneos-sdk
monitor_speed = 115200

build_flags =
    -Ilib
    -Iapp

build_src_filter =
    +<main.c>
    +<lib/*.c>
    +<app/*.c>