[platformio]
# Set the source directory to the parent 'submission' folder
# so PlatformIO sees both the 'app' and 'lib' subfolders
src_dir = task3/submission
include_dir = task3/submission/lib

[env:vsdsquadron_mini]
platform = ch32v
board = vsdsquadronMini
framework = noneos-sdk
monitor_speed = 115200
# Ensures the compiler knows where to find the header file
build_flags = -Itask3/submission/lib